---
- name: Install Nginx
  hosts: your_target_server
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Nginx
      apt:
        name: nginx
        state: present

    - name: Copy index.html
      copy:
        src: /path/to/your/project/index.html
        dest: /var/www/html/index.html
